In [19]:
import pandas as pd
import numpy as np

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

In [22]:
df=pd.read_csv("crop_yield.csv")
df

Crop  Crop_Year       Season              State      Area  \
0           Arecanut       1997  Whole Year               Assam   73814.0   
1          Arhar/Tur       1997  Kharif                   Assam    6637.0   
2        Castor seed       1997  Kharif                   Assam     796.0   
3           Coconut        1997  Whole Year               Assam   19656.0   
4       Cotton(lint)       1997  Kharif                   Assam    1739.0   
...              ...        ...          ...                ...       ...   
19684  Small millets       1998  Kharif                Nagaland    4000.0   
19685          Wheat       1998  Rabi                  Nagaland    1000.0   
19686          Maize       1997  Kharif       Jammu and Kashmir  310883.0   
19687           Rice       1997  Kharif       Jammu and Kashmir  275746.0   
19688          Wheat       1997  Rabi         Jammu and Kashmir  239344.0   

       Production  Annual_Rainfall   Fertilizer  Pesticide        Yield  
0           56708           2051.4   7024878.38   22882.34     0.796087  
1            4685           2051.4    631643.29    2057.47     0.710435  
2              22           2051.4     75755.32     246.76     0.238333  
3       126905000           2051.4   1870661.52    6093.36  5238.051739  
4             794           2051.4    165500.63     539.09     0.420909  
...           ...              ...          ...        ...          ...  
19684        2000           1498.0    395200.00    1160.00     0.500000  
19685        3000           1498.0     98800.00     290.00     3.000000  
19686      440900           1356.2  29586735.11   96373.73     1.285000  
19687        5488           1356.2  26242746.82   85481.26     0.016667  
19688      392160           1356.2  22778368.48   74196.64     1.261818  

[19689 rows x 10 columns]

In [23]:
df.tail()

Crop  Crop_Year       Season              State      Area  \
19684  Small millets       1998  Kharif                Nagaland    4000.0   
19685          Wheat       1998  Rabi                  Nagaland    1000.0   
19686          Maize       1997  Kharif       Jammu and Kashmir  310883.0   
19687           Rice       1997  Kharif       Jammu and Kashmir  275746.0   
19688          Wheat       1997  Rabi         Jammu and Kashmir  239344.0   

       Production  Annual_Rainfall   Fertilizer  Pesticide     Yield  
19684        2000           1498.0    395200.00    1160.00  0.500000  
19685        3000           1498.0     98800.00     290.00  3.000000  
19686      440900           1356.2  29586735.11   96373.73  1.285000  
19687        5488           1356.2  26242746.82   85481.26  0.016667  
19688      392160           1356.2  22778368.48   74196.64  1.261818

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19689 entries, 0 to 19688
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Crop             19689 non-null  object 
 1   Crop_Year        19689 non-null  int64  
 2   Season           19689 non-null  object 
 3   State            19689 non-null  object 
 4   Area             19689 non-null  float64
 5   Production       19689 non-null  int64  
 6   Annual_Rainfall  19689 non-null  float64
 7   Fertilizer       19689 non-null  float64
 8   Pesticide        19689 non-null  float64
 9   Yield            19689 non-null  float64
dtypes: float64(5), int64(2), object(3)
memory usage: 1.5+ MB


In [25]:
df.describe()

Crop_Year          Area    Production  Annual_Rainfall  \
count  19689.000000  1.968900e+04  1.968900e+04     19689.000000   
mean    2009.127584  1.799266e+05  1.643594e+07      1437.755177   
std        6.498099  7.328287e+05  2.630568e+08       816.909589   
min     1997.000000  5.000000e-01  0.000000e+00       301.300000   
25%     2004.000000  1.390000e+03  1.393000e+03       940.700000   
50%     2010.000000  9.317000e+03  1.380400e+04      1247.600000   
75%     2015.000000  7.511200e+04  1.227180e+05      1643.700000   
max     2020.000000  5.080810e+07  6.326000e+09      6552.700000   

         Fertilizer     Pesticide         Yield  
count  1.968900e+04  1.968900e+04  19689.000000  
mean   2.410331e+07  4.884835e+04     79.954009  
std    9.494600e+07  2.132874e+05    878.306193  
min    5.417000e+01  9.000000e-02      0.000000  
25%    1.880146e+05  3.567000e+02      0.600000  
50%    1.234957e+06  2.421900e+03      1.030000  
75%    1.000385e+07  2.004170e+04      2.388889  
max    4.835407e+09  1.575051e+07  21105.000000

In [26]:
df.isnull().sum()

Crop               0
Crop_Year          0
Season             0
State              0
Area               0
Production         0
Annual_Rainfall    0
Fertilizer         0
Pesticide          0
Yield              0
dtype: int64

In [27]:
c=df["Crop"].nunique()
print(c)
s=df["Season"].nunique()
print(s)
s1=df["State"].nunique()
print(s1)

55
6
30


In [39]:
df_encoded=pd.get_dummies(df,columns=["Crop","Season","State"],drop_first=True)

In [40]:
df_encoded.isnull().sum()

Crop_Year              0
Area                   0
Production             0
Annual_Rainfall        0
Fertilizer             0
                      ..
State_Telangana        0
State_Tripura          0
State_Uttar Pradesh    0
State_Uttarakhand      0
State_West Bengal      0
Length: 95, dtype: int64

In [41]:
df_encoded.describe()

Crop_Year          Area    Production  Annual_Rainfall  \
count  19689.000000  1.968900e+04  1.968900e+04     19689.000000   
mean    2009.127584  1.799266e+05  1.643594e+07      1437.755177   
std        6.498099  7.328287e+05  2.630568e+08       816.909589   
min     1997.000000  5.000000e-01  0.000000e+00       301.300000   
25%     2004.000000  1.390000e+03  1.393000e+03       940.700000   
50%     2010.000000  9.317000e+03  1.380400e+04      1247.600000   
75%     2015.000000  7.511200e+04  1.227180e+05      1643.700000   
max     2020.000000  5.080810e+07  6.326000e+09      6552.700000   

         Fertilizer     Pesticide         Yield  Crop_Arhar/Tur    Crop_Bajra  \
count  1.968900e+04  1.968900e+04  19689.000000    19689.000000  19689.000000   
mean   2.410331e+07  4.884835e+04     79.954009        0.025801      0.026614   
std    9.494600e+07  2.132874e+05    878.306193        0.158546      0.160956   
min    5.417000e+01  9.000000e-02      0.000000        0.000000      0.000000   
25%    1.880146e+05  3.567000e+02      0.600000        0.000000      0.000000   
50%    1.234957e+06  2.421900e+03      1.030000        0.000000      0.000000   
75%    1.000385e+07  2.004170e+04      2.388889        0.000000      0.000000   
max    4.835407e+09  1.575051e+07  21105.000000        1.000000      1.000000   

        Crop_Banana  ...  State_Odisha  State_Puducherry  State_Punjab  \
count  19689.000000  ...  19689.000000      19689.000000  19689.000000   
mean       0.012443  ...      0.038600          0.034029      0.020164   
std        0.110857  ...      0.192645          0.181309      0.140563   
min        0.000000  ...      0.000000          0.000000      0.000000   
25%        0.000000  ...      0.000000          0.000000      0.000000   
50%        0.000000  ...      0.000000          0.000000      0.000000   
75%        0.000000  ...      0.000000          0.000000      0.000000   
max        1.000000  ...      1.000000          1.000000      1.000000   

       State_Sikkim  State_Tamil Nadu  State_Telangana  State_Tripura  \
count  19689.000000      19689.000000     19689.000000   19689.000000   
mean       0.011478          0.041749         0.020164       0.022398   
std        0.106524          0.200021         0.140563       0.147979   
min        0.000000          0.000000         0.000000       0.000000   
25%        0.000000          0.000000         0.000000       0.000000   
50%        0.000000          0.000000         0.000000       0.000000   
75%        0.000000          0.000000         0.000000       0.000000   
max        1.000000          1.000000         1.000000       1.000000   

       State_Uttar Pradesh  State_Uttarakhand  State_West Bengal  
count         19689.000000       19689.000000       19689.000000  
mean              0.041902           0.038803           0.055564  
std               0.200369           0.193131           0.229084  
min               0.000000           0.000000           0.000000  
25%               0.000000           0.000000           0.000000  
50%               0.000000           0.000000           0.000000  
75%               0.000000           0.000000           0.000000  
max               1.000000           1.000000           1.000000  

[8 rows x 95 columns]

In [42]:
x=df_encoded.drop('Yield',axis=1)
y=df_encoded['Yield']

In [43]:
x_train,x_test,y_train,y_test=train_test_split(x, y,test_size=0.2,random_state=42)

In [44]:
numeric_cols=["Crop_Year","Area","Production","Annual_Rainfall","Fertilizer","Pesticide"]

In [46]:
scaler=StandardScaler()
x[numeric_cols]=scaler.fit_transform(x[numeric_cols])

In [47]:
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred_lr=lr.predict(x_test)
print(y_pred_lr)

[ 12.33779558   0.95352549  -8.71963681 ... 142.65557015  15.85802502
  23.26316905]


In [48]:
dt=DecisionTreeRegressor(random_state=42)
dt.fit(x_train,y_train)
y_pred_dt=dt.predict(x_test)
print(y_pred_dt)

[4.13       1.45507937 6.52636364 ... 2.56117647 0.5675     0.36842105]


In [49]:
rf= RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(x_train,y_train)
y_pred_rf=rf.predict(x_test)
print(y_pred_rf)

[4.23142545 1.36913899 6.61517627 ... 1.44869736 0.68351079 0.34790703]


In [50]:
gb=GradientBoostingRegressor(random_state=42)
gb.fit(x_train,y_train)
y_pred_gb=gb.predict(x_test)
print(y_pred_gb)

[1.95554339 1.95554339 7.02890938 ... 3.40481929 2.36413885 2.36413885]


In [51]:
def evaluate(y_test,y_pred,name):
    print(f"\n{name}")
    print("MAE :",mean_absolute_error(y_test,y_pred))
    print("MSE:",mean_squared_error(y_test,y_pred))
    print("R2  :",r2_score(y_test,y_pred))

In [61]:
evaluate(y_test,y_pred_lr,"Linear Regression")
evaluate(y_test,y_pred_dt,"Decision Tree")
evaluate(y_test,y_pred_rf,"Random Forest")
evaluate(y_test,y_pred_gb,"Gradient Boosting")


Linear Regression
MAE : 62.98004621362007
MSE: 158461.9275973601
R2  : 0.8022291019986634

Decision Tree
MAE : 11.149846106626713
MSE: 42016.19696040984
R2  : 0.9475610253550916

Random Forest
MAE : 7.260829980458314
MSE: 9921.952295077946
R2  : 0.9876167515751166

Gradient Boosting
MAE : 10.039235234520177
MSE: 12571.038972916587
R2  : 0.9843105173325878


# PREDICTION OF NEW DATA USING RANDOMFOREST

In [62]:
new_data = pd.DataFrame({
    'Crop':['Rice'],
    'Crop_Year':[2024],
    'Season':['Kharif'],
    'State':['Tamil Nadu'],
    'Area':[1200],
    'Annual_Rainfall':[900],
    'Fertilizer':[60],
    'Pesticide':[15]
})


In [63]:
new_data_encoded=pd.get_dummies(new_data,columns=["Crop","Season","State"],drop_first=True)

In [64]:
new_data_encoded=new_data_encoded.reindex(columns=x_train.columns,fill_value=0)

In [67]:
new_data_encoded[numeric_cols]=scaler.transform(new_data_encoded[numeric_cols])

In [70]:
predicted_yield=rf.predict(new_data_encoded)[0]
print("predicted yield",predicted_yield)

predicted yield 79.5697043955999


In [76]:
threshold=y.median()
if predicted_yield>=threshold:
    decision="YES – High Yield Expected"
else:
    decision="NO – Low Yield Expected"
print("Predicted Yield:",predicted_yield)
print("Decision:",decision)

Predicted Yield: 79.5697043955999
Decision: YES – High Yield Expected
